
from operator import attrgetter
import pyangbind.lib.xpathhelper as xpathhelper
from pyangbind.lib.yangtypes import RestrictedPrecisionDecimalType, RestrictedClassType, TypedListType
from pyangbind.lib.yangtypes import YANGBool, YANGListType, YANGDynClass, ReferenceType
from pyangbind.lib.base import PybindBase
from decimal import Decimal
from bitarray import bitarray
class config(PybindBase):
  """
  This class was auto-generated by the PythonClass plugin for PYANG
  from YANG module openconfig-routing-policy - based on the path /routing-policy/policy-definitions/policy-definition/statements/statement/conditions/bgp-conditions/as-path-length/config. Each member element of
  the container is represented as a class variable - with a specific
  YANG type.

  YANG Description: Configuration data for AS path length condition
  """
  __slots__ = ('_pybind_generated_by', '_path_helper', '_yang_name', '_extmethods', '__operator','__value',)

  _yang_name = 'config'

  _pybind_generated_by = 'container'

  def __init__(self, *args, **kwargs):

    helper = kwargs.pop("path_helper", None)
    if helper is False:
      self._path_helper = False
    elif helper is not None and isinstance(helper, xpathhelper.YANGPathHelper):
      self._path_helper = helper
    elif hasattr(self, "_parent"):
      helper = getattr(self._parent, "_path_helper", False)
      self._path_helper = helper
    else:
      self._path_helper = False

    self._extmethods = False
    self.__operator = YANGDynClass(base=RestrictedClassType(base_type=unicode, restriction_type="dict_key", restriction_arg={u'oc-pol-types:ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}},), is_leaf=True, yang_name="operator", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='identityref', is_config=True)
    self.__value = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['0..4294967295']}, int_size=32), is_leaf=True, yang_name="value", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='uint32', is_config=True)

    load = kwargs.pop("load", None)
    if args:
      if len(args) > 1:
        raise TypeError("cannot create a YANG container with >1 argument")
      all_attr = True
      for e in self._pyangbind_elements:
        if not hasattr(args[0], e):
          all_attr = False
          break
      if not all_attr:
        raise ValueError("Supplied object did not have the correct attributes")
      for e in self._pyangbind_elements:
        nobj = getattr(args[0], e)
        if nobj._changed() is False:
          continue
        setmethod = getattr(self, "_set_%s" % e)
        if load is None:
          setmethod(getattr(args[0], e))
        else:
          setmethod(getattr(args[0], e), load=load)

  def _path(self):
    if hasattr(self, "_parent"):
      return self._parent._path()+[self._yang_name]
    else:
      return [u'routing-policy', u'policy-definitions', u'policy-definition', u'statements', u'statement', u'conditions', u'bgp-conditions', u'as-path-length', u'config']

  def _get_operator(self):
    """
    Getter method for operator, mapped from YANG variable /routing_policy/policy_definitions/policy_definition/statements/statement/conditions/bgp_conditions/as_path_length/config/operator (identityref)

    YANG Description: type of comparison to be performed
    """
    return self.__operator
      
  def _set_operator(self, v, load=False):
    """
    Setter method for operator, mapped from YANG variable /routing_policy/policy_definitions/policy_definition/statements/statement/conditions/bgp_conditions/as_path_length/config/operator (identityref)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_operator is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_operator() directly.

    YANG Description: type of comparison to be performed
    """
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=unicode, restriction_type="dict_key", restriction_arg={u'oc-pol-types:ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}},), is_leaf=True, yang_name="operator", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='identityref', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """operator must be of a type compatible with identityref""",
          'defined-type': "openconfig-bgp-policy:identityref",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=unicode, restriction_type="dict_key", restriction_arg={u'oc-pol-types:ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}},), is_leaf=True, yang_name="operator", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='identityref', is_config=True)""",
        })

    self.__operator = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_operator(self):
    self.__operator = YANGDynClass(base=RestrictedClassType(base_type=unicode, restriction_type="dict_key", restriction_arg={u'oc-pol-types:ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'oc-pol-types:ATTRIBUTE_GE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_EQ': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}, u'ATTRIBUTE_LE': {'@module': u'openconfig-policy-types', '@namespace': u'http://openconfig.net/yang/policy-types'}},), is_leaf=True, yang_name="operator", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='identityref', is_config=True)


  def _get_value(self):
    """
    Getter method for value, mapped from YANG variable /routing_policy/policy_definitions/policy_definition/statements/statement/conditions/bgp_conditions/as_path_length/config/value (uint32)

    YANG Description: value to compare with the community count
    """
    return self.__value
      
  def _set_value(self, v, load=False):
    """
    Setter method for value, mapped from YANG variable /routing_policy/policy_definitions/policy_definition/statements/statement/conditions/bgp_conditions/as_path_length/config/value (uint32)
    If this variable is read-only (config: false) in the
    source YANG file, then _set_value is considered as a private
    method. Backends looking to populate this variable should
    do so via calling thisObj._set_value() directly.

    YANG Description: value to compare with the community count
    """
    try:
      t = YANGDynClass(v,base=RestrictedClassType(base_type=long, restriction_dict={'range': ['0..4294967295']}, int_size=32), is_leaf=True, yang_name="value", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='uint32', is_config=True)
    except (TypeError, ValueError):
      raise ValueError({
          'error-string': """value must be of a type compatible with uint32""",
          'defined-type': "uint32",
          'generated-type': """YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['0..4294967295']}, int_size=32), is_leaf=True, yang_name="value", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='uint32', is_config=True)""",
        })

    self.__value = t
    if hasattr(self, '_set'):
      self._set()

  def _unset_value(self):
    self.__value = YANGDynClass(base=RestrictedClassType(base_type=long, restriction_dict={'range': ['0..4294967295']}, int_size=32), is_leaf=True, yang_name="value", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, namespace='http://openconfig.net/yang/bgp-policy', defining_module='openconfig-bgp-policy', yang_type='uint32', is_config=True)

  operator = property(_get_operator, _set_operator)
  value = property(_get_value, _set_value)


  _pyangbind_elements = {'operator': operator, 'value': value, }


